Yaml parsing
nostressdev/fdb pull request #4
Opened 2022-05-18 19:26 UTC by levtul

2022-05-18 19:37 UTC, luckybet100 requested changes

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/yaml/parse.go
> +func main() {
это явно должно быть не тут. лучше всего сделать так. посмотри как делал Женя в chill cloud

https://github.com/chill-cloud/chill-cli/blob/master/main.go

есть папчка cmd, где описаны все компанды. main.go, который их умеет запускать. ну и описание и тд

2022-05-18 19:37 UTC, luckybet100 commented on config.yaml
> +models:
я так понимаю это какие-то тестовые данные. Они должны попадать в раздел тестов, но явно не в корень самого проекта. Я бы создал папочку tests, где разместил этот файл + еще тесты

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/scheme.go
> +func (c *GeneratorConfig) Validate() error {
Давай мы сделаем код, более читаемым

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/scheme.go
> +	for _, model := range c.Models {
Вот это вынесем в одну функцию

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/scheme.go
> +	for _, table := range c.Tables {
Вот это в другую

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/scheme.go
> +		for _, index := range table.RangeIndexes {
Это в третью

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/yaml/parse.go
> +func (p *Parser) parseConfig(text string) (*scheme.GeneratorConfig, error) {
Забавно что функция приватная и никак ее поюзать не выйдет

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/yaml/parse.go
> +		for _, field := range model.Fields {
давай разнесем по отдельным функциям

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/yaml/parse.go
> +	for _, table := range config.Tables {
тоже самое

2022-05-18 19:37 UTC, luckybet100 commented on orm/scheme/scheme.go
> +			if _, ok := columnsSet[column.Name]; ok {
тоже в отдельную функцию

2022-05-18 19:52 UTC, luckybet100 commented on go.mod
> +go 1.17
1.18

2022-05-19 08:15 UTC, luckybet100 requested changes

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/errors/erros.go
> +package errors
- Переименовать файл в errors с erros
- Переместить пакет в корень
- Написать тесты

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/errors/erros.go
> +	return err.originalError.Error()
Возможно, имеет смысл добавить описание ошибки, тоесть условно

VALIDATION ERROR: xxxx

офк, только если не NoType

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +func (p *ValuesParser) parseModel(value interface{}, model scheme.Model) (interface{}, error) {
почему возвращает interface{}, где это не надо. аналогично почему value, имеет тип interface{} Воняет питоном

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +	if fieldsMap, ok = value.(map[string]interface{}); !ok {
ну вот ты сам понимаешь, абсурдность этого if. Ты проверяешь что то что ты передаешь в аргументах, именно определенный тип. Зачем этот python стайл. Сделай просто тип у value

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +package parser
Я вообще не большой любитель паник, но этот файл это тот случай, когда их поюзать правильно. ParseValues, должен возвращать ошибку, а остальные вещи, должны бросать паники и код станет в несколько раз более читаемым

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +			if field.DefaultValue != nil {
а почему не добавить проверку на nil, внутрь parse filed, и избежать 2 ифов внутри друг друга

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +			if column.DefaultValue != nil {
аналогично тому что выше

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/parser/parse.go
> +			continue
помечай места где ты что-то не написал, как // TODO

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
> +func (c *GeneratorConfig) validateModels() error {
я вы вообще все эти функции в отдельный файл вынес

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
> +
комент про паники актуален и тут

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
> +		if _, ok := columnsSet[column.Name]; ok {
аналогично выше про колонку

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
> +		if _, ok := indexesSet[index.Name]; ok {
аналогично выше

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
> +	for _, model := range c.Models {
А давай у модели, просто будет функция Validate, которая будет вызываться

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/yaml/parse.go
> +	config := &scheme.GeneratorConfig{}
Мне кажется, что тут есть одна глобальная проблема, которая заключается в том, что у тебя парсинг и валидация с друг другом перемешались. Как я понимаю, основная причина зачем нужен ValuesParser - спарсить дефолтные значения. В моем понимании, должен быть вначале один процесс - парсинг. Который может бросать ParseError, а потом процесс валидация. Соотвественно, парсинг значений - часть процесса парсинга. Соответственно, когда у тебя что-то не так при парсинге, это не ошибка валидации - а ошибка парсинга. А ошибка валидации, это когда ты позже к примеру поймаешь бесконечный цикл в офисаниях моделей

2022-05-19 08:15 UTC, luckybet100 commented on orm/scheme/scheme.go
>  type Model struct {
А теперь давай напишем классный тест, где у тебя модель A, будет юзать модель Б и наоборот, получим бесконечный цикл.

Надо написать проверку графа на ацикличность в валидаторе

2022-05-19 08:15 UTC, luckybet100 commented on test/fuzz_test.go
> +func FuzzParseYaml(f *testing.F) {
Этот тест норм, но я хочу еще более разумный fuzzing тест, где у меня не просто рандомная строка будет передаваться, а как-то адекватно тест строиться, то есть чтобы у тебя более корректные тесты на вход подавались

2022-05-19 08:15 UTC, luckybet100 commented on test/fuzz_test.go
> +package test
Надо добавить много обычных тестов

2022-05-19 08:15 UTC, luckybet100 commented on test/fuzz_test.go
> +package test
не должно быть отдельной папки test, в го так не принято. В го принято, если есть файл xx.go, то тесты к функциям в нем будут называться xx_test.go и лежать в той же папке

2022-05-21 21:50 UTC, luckybet100 requested changes

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +			if newValue, ok := value.(map[string]interface{}); ok {
мне не нравится if внутри if-а, не то чтобы предлагаю прям мега конкретное, что-то, но условно if, который strings.HasPrefix(fieldType, "@"), можно было бы поменять на просто :

if newValue, ok := value.(map[string]interface{}); ok && strings.HasPrefix(fieldType, "@")

ну или вообще я мб бы отказался от этой собачки и убрал это, потому что никакого особого смысла собачка не несет

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	err := json.NewDecoder(reader).Decode(config)
зачем ты дублируешь логику. Вот я щас выше предложил поменять и тебе придется менять в 3 местах. Надо было сделать:

return p.AddDecoder(json.NewDecoder(reader))

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	err := yaml.NewDecoder(reader).Decode(config)
аналогично тому что выше

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +func (p *Parser) AddJSONReader(reader io.Reader) error {
давай назовем просто, это AddJSON

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +func (p *Parser) AddYAMLReader(reader io.Reader) error {
давай назовем просто AddYAML

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	Models  map[string]scheme.Model
глобально все гуд, только давай везде поменяет scheme.Model и scheme.Table, на *scheme.Model и *scheme.Table, а то много лишних кориваний

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		err := p.parseValues(config)
а зачем делать так, почему не сделать recover именно в функции GetConfig?

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	models := make([]scheme.Model, 0)
либо давай сделаем в один цикл и сразу после parseValues сделаем append, либо давай посчитаем размеры и сделаем здесь reserve (желаемый capacity - третий параметр у make). Учитывая то, что у нас и так много аллокаций и мы по этому поводу особо не паримся (да и не имеет это особо смысла тут) - предпочитаю первый вариант

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +func (p *Parser) GetConfig() (*scheme.GeneratorConfig, error) {
Давай просто в Parse переименуем, мне так кажется почему-то логичнее

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	for name, value := range fieldsMap {
у тебя параметр входной value и тут значение value - не круто

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	fieldsMap := value
а давай мы просто аргумент, который называется value переименуем в fieldsMap и не будем делать лишних присвоений

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		modelFieldNames[field.Name] = i
как я понимаю, здесь значение i по сути никак не используется, это просто map, чтобы проверять наличие имени. Классно, а давай просто сделаем ее map[string]bool, тогда 

if _, ok := modelFieldNames[name]; !ok {

превратится в просто if modelFieldNames[name]

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +func (p *Parser) parseModel(value map[string]interface{}, model scheme.Model) map[string]interface{} {
название меня немного запутало, давай переименуем в parseModelValues, потому что иначе кажется, что parseModel - то что должно вызываться из parseModels

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	return fieldsMap
а здесь у тебя вот конкретный багос. Объясню плчему. Как я понял, если я в модельке укажу дефолтные значения, а потом в колонке задам тип из этой модельник и укажу дефолтное значение, но не все поля. Тогда у тебя дефолтные значения из модельки самой не проставятся. Пример

модель User, поля name, surname -дефолтные значения Ivan Ivanov

таблица состоит из модели User и все и в дефолтных значениях, я укзал модель User и только у name дефолтное значение Petya. Тогда я ожидаю, что в таблице все по дефолту Пети Ивановы, а по факту, будут Пети без фамилии

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		return uint64(value.(int))
я уверен, что это НЕ работает

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		return uint32(value.(int))
я уверен, что это НЕ работает

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +package parser
про все баги, которые я написал ниже - надо добавить тесты

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +func (model *Model) validate() {
потом, будет такой же validate у индексов, колонок и тд. давай мы лучше сделаем файлы:

model.go, column.go, rangeindex.go и тд

валидация, которая относится непосредственно к модели - должна идти туда

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +	set := make(map[string]struct{})
сделай map[string]bool, как я писал выше - станет чище

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +	columnsSet := make(map[string]struct{})
map[string]bool

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +	indexesSet := make(map[string]struct{})
map[string]bool

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +package scheme
давай глобально прям в этом пакете создадим файл, utils и сделаем две функции

 validate(expression bool, text string) и validatef(expression bool, form string, args ...interface{})
 
 если expression false - бросает панику, которая делается как panic(errors.ValidationError.Newf()) или panic(errors.ValidationError.New()) в зависимости от понятно чего. Код ниже станет читаемей

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +		if index.Name == "" {
почему это тут, почему у тебя у индекса нет функции validate, аналогично модели, которая бы это делала? Эта функция, вполне может принимать объект *scheme.Table, ибо он ей реально нужен. Ну а вообще я думаю, что будет полезно в саму структуру добавить *scheme.Table. Ибо потом это будет очень надо Кучуму

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +func (c *GeneratorConfig) validateIndexes(table *Table, columnsSet map[string]struct{}) {
columnsSet map[string]bool

2022-05-21 21:50 UTC, luckybet100 commented on orm/scheme/validate.go
> +func (c *GeneratorConfig) Validate() (err error) {
все еще нет проверки на ацикличность, а я ее очень жду

2022-05-21 21:50 UTC, luckybet100 commented on test/fuzz_test.go
> +package test
Очень жду тесты, прям на каждую функцию

2022-05-21 21:57 UTC, luckybet100 commented on orm/scheme/validate.go
> +	tablesSet := make(map[string]struct{})
map[string]bool

2022-05-21 21:58 UTC, luckybet100 commented on orm/scheme/validate.go
> +		if table.StoragePath == "" {
давай StoragePath вообще полностью пока уберем

2022-05-21 22:00 UTC, luckybet100 commented on orm/scheme/parser/parser_test.go
> +			if err == nil {
а давай проверять еще и что это именно ValidationError

2022-05-21 22:11 UTC, luckybet100 commented on orm/scheme/validate.go
> +func (c *GeneratorConfig) checkCycles() {
oh my god!
я многое ожидал увидеть, но точно не проверку на ацикличность dfs со стеком руками. Это 100% невозможно читать. 

Давай у нас будет пакет, graph. В папке utils. Там будет interface Graph со следующеми методами, AddVertext(string), AddEdge(string, string) и func IsCyclic() (bool, list<string>). IsCyclic внутри создает map[string]bool visited для посещенных и map[string]bool recursionStack, далее запускает обычный рекурсивный dfs. Если мы встречаем посещенную вершину, которая есть в стеке рекурсии - мы его разворачиваем и генерируем список вершин. В итоговой ошибке, я хочу чтобы было понятно - какие конкретно модели образуют цикл. Поэтому я хочу чтобы прям подробно был описан цикл. Все станет читаемей, заодно тестить реализацию можно будет независимо от этого всего

2022-05-21 22:18 UTC, luckybet100 requested changes

2022-05-21 22:18 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +func NewParser() *Parser {
просто New, потому что когда ты будешь извне юзать, это будет выглядеть как parser.New

2022-05-21 22:19 UTC, luckybet100 commented on orm/scheme/validate.go
> +var primitives = map[string]struct{}{
map[string]bool тоже судя по всему)

2022-05-21 22:21 UTC, luckybet100 commented on errors/errors.go
> +package errors
сюда тоже хорошо бы хотябы какие-то базовые тестики подабовлять

2022-05-21 22:31 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		return err
стоит в parse error обернуть

2022-05-21 22:33 UTC, luckybet100 commented on orm/scheme/validate.go
> +	modelsSet := make(map[string]struct{})
map[string]bool

2022-05-22 08:33 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	err := decoder.Decode(config)
самая последняя правка здесь - давай deode при парсинге делать, а тут просто список декодеров сохраним

2022-05-22 08:36 UTC, luckybet100 commented on orm/scheme/rangeIndex.go
> +func (index *RangeIndex) validate(columnsSet map[string]bool) {
раз у тебя внутри хранится таблица - мне кажется это бесмыслено передавать

2022-05-22 08:38 UTC, luckybet100 commented on orm/scheme/utils/graph/graph.go
> +	path = path[:len(path)-1]
это совсем не работает)

2022-05-22 12:57 UTC, luckybet100 commented on errors/errors_test.go
> +	err := ParsingError.New("error")
Оформи как табличные тесты

2022-05-22 12:58 UTC, luckybet100 commented on errors/errors_test.go
> +	err := errors.New("error")
Тоже оформи как табличные тесты со всеми типами ошибок

2022-05-22 12:58 UTC, luckybet100 commented on errors/errors_test.go
> +	err := ParsingError.New("error")
Аналогично

2022-05-22 13:09 UTC, luckybet100 requested changes

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	Configs  []*scheme.GeneratorConfig
Вот это поле сейчас судя по всему стало лишним

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +	case "int64": // yaml parses int64 as int on 64bit and as int64 on 32bit
Давай распишем многострочный коммент, где чуть подробнее на будущее опишем проблему и всё-таки это не только yaml касается

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/parser/parser.go
> +		Configs: []*scheme.GeneratorConfig{},
Я сказал убрать это поле, но я просто скажу на будущее. Пустой слайс и nil это одно и тоже)
append(nil, value) прекрасно работает

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/utils/graph/graph.go
> +		if g.isCyclic(node, visited, &path) {
Как мне кажется тут всё-таки надо только от непосещенных запускаться. Вроде как ничего не ломается сейчас, но это бессмысленно

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/utils/graph/graph.go
> +func (g *Graph) isCyclic(node string, visited map[string]int, path *[]string) bool {
Сложно и не читаемо. Указатель на path, фуфуфу. Почему бы просто не сделать, чтобы функция возвращала path и bool. Станет куда понятнее. Ну и давай константы 0,1,2 назовём как-то NotVisited, InProgress, Done, ну или если придумаешь другие названия меня тоже утсромт

2022-05-22 13:09 UTC, luckybet100 commented on orm/scheme/utils/utils.go
> +package utils
Просто чтобы не уменьшать процент покрытия тестами, давай и сюда пару тестов добавим

2022-05-22 13:15 UTC, luckybet100 requested changes

2022-05-22 13:15 UTC, luckybet100 commented on orm/scheme/validate.go
> +			if ok := primitives[field.Type]; ok {
Все ещё не надо с ok делать)

2022-05-22 23:08 UTC, luckybet100 requested changes

2022-05-22 23:08 UTC, luckybet100 commented on orm/scheme/utils/utils_test.go
> +			defer func() {
есть (https://pkg.go.dev/github.com/stretchr/testify@v1.7.1/assert), так есть методы для проверки паник

2022-05-22 23:08 UTC, luckybet100 commented on orm/scheme/validate_test.go
> +			if err := c.Validate(); (err != nil) != tt.wantErr {
testify.assert и testify.require твои лучшие друзья

https://pkg.go.dev/github.com/stretchr/testify@v1.7.1/assert

2022-05-22 23:08 UTC, luckybet100 commented on orm/scheme/utils/utils_test.go
> +			Validate(tt.args.expression, tt.args.text)
https://pkg.go.dev/github.com/stretchr/testify@v1.7.1/assert

2022-05-22 23:13 UTC, luckybet100 commented on orm/scheme/parser/parser_test.go
> +			parser.AddYAML(strings.NewReader(string(text)))
можно просто  os.Open(tt.filename) передать как reader

2022-05-24 03:15 UTC, MKuchum commented on orm/scheme/utils/graph/graph.go
> +		if visited[node] == 0 {
Хорошо бы использовать константы, по типу `visited[node] == NotVisited`

2022-05-24 03:15 UTC, MKuchum commented on orm/scheme/utils/graph/graph.go
> +		if visited[node] == 0 {
Это относится ко всему файлу

2022-05-24 03:15 UTC, MKuchum commented on orm/scheme/parser/parser.go
> +		fieldsMap[name] = value
Придирка: А почему это не в одну строчку?

2022-05-28 00:44 UTC, merged